#!/bin/bash
gem_current_version() {
  #HACK ALERT.
  gem specification -r $1 | \
    egrep '^ *version: [0-9]+(\.[0-9]+)+' | \
    awk '{ print $2 }'
}

options=$(getopt ":a:" $*)
echo "options='$options'"

args=${options% -- *}
gem_name=${options#* -- }
echo "gem_name=\"$gem_name\", and args=\"$args\""

version=""
#TODO: get version automatically
while getopts ":v:" flag; do
  if [ "$flag" == 'v' ]; then
    version=$OPTARG
  fi
done
if [ -z $version ]; then
  version=$(gem_current_version $gem_name)
fi
echo "using $gem_name version $version"

gem_title=$gem_name-$version

mkdir -p ./rpmbuild/{SOURCES,SPECS}
ls ./template.spec.rb

if [ ! -e rpmbuild/SOURCES/$gem_title.gem ]; then
  echo "Downloading gem $gem_name, version $version"
  cd rpmbuild/SOURCES && gem fetch $gem_name --version $version
  cd ../..
else
  echo "Skipping download of $gem_title"
fi

chmod +x ./template.spec.rb

echo "building spec file..."
./template.spec.rb rpmbuild/SOURCES/$gem_title.gem $args \
  > ./rpmbuild/SPECS/rpgem-$gem_title.spec
echo "done"

if [ -o build ]; then
  cd rpmbuild && \
    rpmbuild -vv -ba SPECS/rpgem-$gem_title.spec
fi
